spring.application.name=UserInteraction

server.port=8080

base.url.products-microservice=http://products:8420/api/products
base.url.cart-microservice=http://cart:8421/api/cart
base.url.order-microservice=http://orders:8422/api/order

logging.level.com.UserInteraction.UserInteractionMicroService.client=DEBUG
logging.level.feign=DEBUG