spring.application.name=UserInteraction

server.port=8423

base.url.products-microservice=http://localhost:8420/api/products
base.url.cart-microservice=http://localhost:8421/api/cart
base.url.order-microservice=http://localhost:8422/api/order
